// <auto-generated />
namespace Gradnik_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removed_Staticke_Proracune : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_Staticke_Proracune));
        
        string IMigrationMetadata.Id
        {
            get { return "201809152111073_Removed_Staticke_Proracune"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
