// <auto-generated />
namespace Gradnik_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remove_MaterijaliDostupni : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_MaterijaliDostupni));
        
        string IMigrationMetadata.Id
        {
            get { return "201811111951480_Remove_MaterijaliDostupni"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
